version: 0.2

phases:
  build:
    commands:
      - echo "Zipping Node.js application..."
      - zip -r application.zip app.js package.json
artifacts:
  files:
    - application.zip
  discard-paths: no
