version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
      - echo "Zipping Node.js application..."
      - zip -r application.zip app.js package.json package-lock.json node_modules
artifacts:
  files:
    - application.zip
  discard-paths: no
