version: 0.2

phases:
  build:
    commands:
      - echo "Zipping app.py and requirements.txt..."
      - zip application.zip app.py requirements.txt

artifacts:
  files:
    - application.zip
  discard-paths: no
