version: 0.2

phases:
  build:
    commands:
      - echo "Zipping Node.js application from code directory..."
      - zip application.zip app.js mailModule.js package.json
artifacts:
  files:
    - application.zip
  discard-paths: no
