version: 0.2

phases:
  build:
    commands:
      - echo "Creating zip file of the entire application..."
      - zip -r application.zip . -x "terraform/*" ".git/*" ".DS_Store" ".gitignore"
artifacts:
  files:
    - application.zip
  discard-paths: no
